'use strict';

export const ROLES = {
  ADMIN: 'ADMIN',
  TENANT: 'TENANT',
  OWNER: 'OWNER',
};

export const PROPERTY_TYPES = {
  HOUSE: 'HOUSE',
  APARTMENT: 'APARTMENT',
  CONDO: 'CONDO',
  LAND: 'LAND',
  COMMERCIAL: 'COMMERCIAL',
  TOWNHOUSE: 'TOWNHOUSE',
  FARM: 'FARM',
};

export const LISTING_TYPES = {
  SALE: 'SALE',
  RENT: 'RENT',
  BOTH: 'BOTH',
};

export const PROPERTY_STATUS = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  ACTIVE: 'ACTIVE',
  SOLD: 'SOLD',
  RENTED: 'RENTED',
  INACTIVE: 'INACTIVE',
  UNDER_CONTRACT: 'UNDER_CONTRACT',
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const TRANSACTION_STATUS = {
  NEGOTIATION: 'NEGOTIATION',
  CONTRACT: 'CONTRACT',
  SOLD: 'SOLD',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED',
};

export const TRANSACTION_TYPES = {
  SALE: 'SALE',
  RENTAL: 'RENTAL',
};

export const DOCUMENT_TYPES = {
  DEED: 'DEED',
  TITLE: 'TITLE',
  SURVEY: 'SURVEY',
  INSPECTION: 'INSPECTION',
  TAX_RECORD: 'TAX_RECORD',
  INSURANCE: 'INSURANCE',
  CONTRACT: 'CONTRACT',
  LEASE: 'LEASE',
};

export const NOTIFICATION_TYPES = {
  INQUIRY: 'INQUIRY',
  PAYMENT: 'PAYMENT',
  VERIFICATION: 'VERIFICATION',
  CONTRACT: 'CONTRACT',
  REMINDER: 'REMINDER',
  SHOWING: 'SHOWING',
  MAINTENANCE: 'MAINTENANCE',
};

export const SHOWING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  RESCHEDULED: 'RESCHEDULED',
};

export const MAINTENANCE_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const MAINTENANCE_STATUS = {
  SUBMITTED: 'SUBMITTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  ON_HOLD: 'ON_HOLD',
};

export const ESCROW_STATUS = {
  DEPOSITED: 'DEPOSITED',
  HELD: 'HELD',
  RELEASED_TO_SELLER: 'RELEASED_TO_SELLER',
  REFUNDED_TO_BUYER: 'REFUNDED_TO_BUYER',
  DISPUTED: 'DISPUTED',
};

export const ALERT_FREQUENCY = {
  IMMEDIATE: 'IMMEDIATE',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
};

export const DOCUMENT_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const OTP_PURPOSES = {
  EMAIL_VERIFICATION: 'email_verification',
  PASSWORD_RESET: 'password_reset',
  TWO_FACTOR: 'two_factor',
};

export default {
  ROLES,
  PROPERTY_TYPES,
  LISTING_TYPES,
  PROPERTY_STATUS,
  VERIFICATION_STATUS,
  PAYMENT_STATUS,
  TRANSACTION_STATUS,
  TRANSACTION_TYPES,
  DOCUMENT_TYPES,
  DOCUMENT_VERIFICATION_STATUS,
  NOTIFICATION_TYPES,
  SHOWING_STATUS,
  MAINTENANCE_PRIORITY,
  MAINTENANCE_STATUS,
  ESCROW_STATUS,
  ALERT_FREQUENCY,
  OTP_PURPOSES,
};
